# image: ruby:2.7

# pages:
#   script:
#     - gem install bundler
#     - bundle install
#     - bundle exec jekyll build -d public
#   artifacts:
#     paths:
#       - public

image: python:latest

before_script:
  - export no_proxy='esrf.fr' 
  - python -V  
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

test:
  script:
    - pip install pytest

pages:
  script:
    - pip install sphinx sphinx-rtd-theme myst-parser furo
    - cd doc
    - make html
    - mv build/html/ ../public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
