# image: ruby:2.7

# pages:
#   script:
#     - gem install bundler
#     - bundle install
#     - bundle exec jekyll build -d public
#   artifacts:
#     paths:
#       - public

# image: python:3.8-bullseye
image: python:3.11-bullseye

before_script:
  - export no_proxy='esrf.fr'
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  # - pip install --pre --find-links https://kmap.gitlab-pages.esrf.fr/xsocs/wheels/ xsocs
  - pip install xsocs
  - pip install -e git+https://gitlab.esrf.fr/id01-science/id01-core.git#egg=id01-core
  - pip install .
  - pip install ipykernel
  - python3 -m ipykernel install --user --name sxdm.slurm

precommit:
  script:
    - pre-commit run --all-files

test:
  script:
    - python tests/xsocs_shift.py
    - python tests/xsocs_qconvert.py
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /run_tests/

pages:
  script:
    - apt-get update
    - apt-get install -y --no-install-recommends pandoc
    - pip install sphinx sphinx-rtd-theme myst-parser furo sphinx-copybutton sphinx-design myst-nb sphinx-autodoc2
    - cd doc
    - make html
    - mv build/html/ ../public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_MESSAGE =~ /build_docs/
