image: python:3.11-bullseye

variables:
  PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"

cache:
  paths:
    - .cache/pip
    - $HOME/.cache/pre-commit
    - .venv

before_script:
  - pip install --upgrade pip
  - pip install poetry
  - poetry config virtualenvs.in-project true
  - poetry install -vv --with dev

stages:
  - lint
  - test
  - build

precommit-linting:
  stage: lint
  script:
    - poetry run pre-commit install-hooks
    - poetry run pre-commit run --all-files

testing:
  stage: test
  script:
    - poetry run pytest tests --junitxml=tests/report.xml
  artifacts:
    when: always
    reports:
      junit: tests/report.xml

  rules:
    - if: $CI_COMMIT_MESSAGE =~ /run_tests/

pages:
  stage: build
  script:
    - apt-get update
    - apt-get install -y --no-install-recommends pandoc
    - poetry run python -m ipykernel install --user --name sxdm.slurm
    - cd doc
    - poetry run make html
    - mv build/html/ ../public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_MESSAGE =~ /build_docs/
