# image: ruby:2.7

# pages:
#   script:
#     - gem install bundler
#     - bundle install
#     - bundle exec jekyll build -d public
#   artifacts:
#     paths:
#       - public

image: python:latest

before_script:
  - python -V  
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

test:
  script:
    - pip install pytest